- hosts: localhost
  become: yes
  vars_files:
    - host_vars/hypervisor
  tasks:
    - name: Prepare hypervisor
      include_tasks: ./initial-setup-hypervisor.yaml

    - name: Create qcow2 for KVMs
      include_tasks: ./qcow2.yaml
